In [1]:
import numpy as np

In [90]:
inp_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
out_data = np.array([[0], [1], [1], [0]])
inp_data, out_data

(array([[0, 0],
        [0, 1],
        [1, 0],
        [1, 1]]),
 array([[0],
        [1],
        [1],
        [0]]))

In [91]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [92]:
def sigmoid_derivative(x):
    return x*(1-x)

In [93]:
inp_dim = 2
hid_dim = 4
out_dim = 1

In [94]:
input_hidden_weights = 2*np.random.random((inp_dim, hid_dim))-1
hidden_output_weights = 2*np.random.random((hid_dim, out_dim))-1
input_hidden_weights, hidden_output_weights

(array([[ 0.5901938 , -0.82682978, -0.8980841 , -0.38988497],
        [-0.89386107, -0.62194502, -0.7378185 ,  0.81605354]]),
 array([[0.66851732],
        [0.31155275],
        [0.10197557],
        [0.55230166]]))

In [95]:
lr = 0.5
epochs = 10000

In [96]:
for i in range(epochs):
    ## Feed Forward 
    hidden_layer_output = sigmoid(np.dot(inp_data, input_hidden_weights))
    output_layer_output = sigmoid(np.dot(hidden_layer_output, hidden_output_weights))

    ## Calculate Output Layer Error
    output_layer_error = out_data - output_layer_output

    ## Back-Propogation to change the hidden_output_weights
    output_layer_delta = output_layer_error * sigmoid_derivative(output_layer_output)
    new_hidden_output_weights = lr * np.dot(hidden_layer_output.T, output_layer_delta)

    ## Calculate Hidden Layer Error
    hidden_layer_error = np.dot(output_layer_delta, hidden_output_weights.T)

    ## Back-Propogation to change the input_hidden_weights
    hidden_layer_delta = hidden_layer_error * sigmoid_derivative(hidden_layer_output)
    new_input_hidden_weights = lr * np.dot(inp_data.T, hidden_layer_delta)

    ## Updating Both layer weights
    input_hidden_weights += new_input_hidden_weights
    hidden_output_weights += new_hidden_output_weights

In [97]:
input_hidden_weights

array([[ 3.26445428,  0.14117219, -5.49217574, -7.18851987],
       [-7.14849163,  0.78978422, -5.68207495,  3.33146163]])

In [98]:
hidden_output_weights

array([[  6.71302591],
       [ -5.27305872],
       [-15.7334267 ],
       [  7.46407698]])

In [99]:
hidden_output = sigmoid(np.dot(inp_data, input_hidden_weights))
predicted_output = sigmoid(np.dot(hidden_output, hidden_output_weights))

In [100]:
predicted_output

array([[0.03183947],
       [0.9715747 ],
       [0.9730036 ],
       [0.02952115]])

In [101]:
output_layer_error

array([[-0.03184129],
       [ 0.02842694],
       [ 0.026998  ],
       [-0.02952292]])

In [102]:
hidden_layer_error

array([[-0.00658932,  0.00517587,  0.01544346, -0.0073265 ],
       [ 0.00527046, -0.00413991, -0.01235242,  0.00586009],
       [ 0.00476091, -0.00373966, -0.01115818,  0.00529353],
       [-0.00567828,  0.00446025,  0.01330824, -0.00631354]])

In [103]:
np.round(predicted_output)

array([[0.],
       [1.],
       [1.],
       [0.]])